- src/main/scripts/ctl/wcs2suite.xml
Updated the user form with the correct conformance class names.
Fixed with this commit:  d001aa8930663a7fba60ebd9945ae99ccb789e4b
> Updated the user form with correct names of conformance classes. #25

- src/main/scripts/ctl/wcs2main.xml
Fixed with this commit: 0586493
> Fixed the checkbox issue #29.

- src/main/scripts/ctl/ext_crs.xml
> Updated the correct input parameters for ext_crs test. 

- src/main/scripts/ctl/ext_crs.xml
> Added missing namespace in request body. 

- src/main/scripts/ctl/wcs2suite.xml
> Added validation to validate service endpoint URL before running test.

- src/main/scripts/ctl/ext_get-int.xml
> Fixed test names in extension 'Interpolation'

- src/main/scripts/ctl/ext_get-int.xml
> Cleaned up extension interpolation

- src/main/scripts/ctl/eowcs_DescribeEOCoverageSet.xml
> Fixed xpath expressions of test wcseo:get-kvp-req63-66

- src/main/scripts/ctl/GetCoverage.xml
- src/main/scripts/ctl/OWSCommon.xml
- src/main/scripts/ctl/eowcs_DescribeEOCoverageSet.xml
- src/main/scripts/ctl/eowcs_get-kvp.xml
> Fixed the request parameter encoding issue

- src/main/scripts/ctl/ext_get-scal.xml
and variables in test wcs2:get-scal-req23
Fixes #43
> Fixed assertion of Requirement 13

- src/main/scripts/ctl/eowcs_main.xml
- src/main/scripts/ctl/ext_crs.xml
- src/main/scripts/ctl/ext_get-int.xml
- src/main/scripts/ctl/ext_get-proc.xml
- src/main/scripts/ctl/ext_get-rsub.xml
- src/main/scripts/ctl/ext_get-scal.xml
- src/main/scripts/ctl/ext_post-xml.xml
- src/main/scripts/ctl/wcs2main.xml
> Configured conformance classes

- pom.xml
- src/assembly/aio.xml
- src/assembly/deps.xml
- src/main/config/config.xml
- src/main/java/org/opengis/cite/wcs20/CtlController.java
- src/main/java/org/opengis/cite/wcs20/TestRunArguments.java
- src/main/java/org/opengis/cite/wcs20/WCS20.java
- src/main/javadoc/index.html
- src/main/javadoc/overview.html
- src/main/resources/META-INF/services/com.occamlab.te.spi.jaxrs.TestSuiteController
- src/main/resources/org/opengis/cite/wcs20/ets.properties
- src/main/resources/org/opengis/cite/wcs20/test-run-props.xml
- src/main/scripts/ctl/wcs2suite-auto.xml
- src/main/scripts/ctl/wcs2suite.xml
Merge this teamengine PR first: https://github.com/opengeospatial/teamengine/pull/363 then wcs20 PR.
Fixes #72
> The ets-wcs20 is enabled with the RESTfull execution.

- pom.xml
- src/assembly/aio.xml
- src/assembly/deps.xml
- src/main/config/config.xml
- src/main/docker/Dockerfile
- src/main/java/org/opengis/cite/wcs20/CtlController.java
- src/main/java/org/opengis/cite/wcs20/TestRunArguments.java
- src/main/java/org/opengis/cite/wcs20/WCS20.java
- src/main/javadoc/index.html
- src/main/javadoc/overview.html
- src/main/resources/META-INF/services/com.occamlab.te.spi.jaxrs.TestSuiteController
- src/main/resources/org/opengis/cite/wcs20/ets.properties
- src/main/resources/org/opengis/cite/wcs20/test-run-props.xml
- src/main/scripts/ctl/wcs2suite-auto.xml
- src/main/scripts/ctl/wcs2suite.xml
> Added docker support

- src/main/scripts/ctl/DescribeCoverage.xml
Merge PR #69 before this PR to avoid conflicts.
Fixed #38.
> Fixed test req21 & req22 issue.

- src/main/scripts/ctl/DescribeCoverage.xml
> Fixed the describe coverage request issue. 

- src/main/scripts/ctl/ext_crs.xml
* wcs2:get-kvp-crs-req13
* wcs2:get-kvp-crs-req21
* wcs2:get-kvp-crs-req24
Fixes #23
> Disabled tests 

- src/main/scripts/ctl/eowcs_EO-data-model.xml
> Fixed test req6 issue with gml-EnvelopeWithTimePeriod. 

- src/main/scripts/ctl/ext_get-int.xml
> Fixed issue in test result by adding missing bracket.

- src/main/scripts/ctl/wcs2main.xml
- src/main/scripts/ctl/wcs2suite-auto.xml
> Added fix for ignored query parameters in service.

- src/main/scripts/ctl/ext_crs.xml
- src/main/scripts/ctl/ext_get-rsub.xml
> Updated the SupportsGML condition with gml URL.

- jenkinsfiles/build/Jenkinsfile
- jenkinsfiles/test/Jenkinsfile
- pom.xml
- src/test/resources/soapui/ets-wcs20-soapui-project.xml
Fixed #71.
This PR should merge after PR: #73 .
> Added SoapUI tests and integrated into Maven and Jenkinsfile

- src/test/resources/soapui/ets-wcs20-soapui-project.xml
Reference: https://github.com/opengeospatial/teamengine/issues/462#issuecomment-799301806
> Added header for soapui test.

- src/main/scripts/ctl/ext_post-xml.xml
> Updated parser to validate the response using content-type.

- src/main/scripts/ctl/ext_get-int.xml
> Updated tests requests with correct axisLabels and InterpolationSupported parameters.

- src/main/scripts/ctl/GetCoverage.xml
- src/main/scripts/ctl/OWSCommon.xml
> Closes #113

- src/main/scripts/ctl/wcs2suite.xml
> Closing #111

- src/main/scripts/ctl/GetCoverage.xml
> Closes #124

- src/main/scripts/ctl/GetCoverage.xml
- src/main/scripts/ctl/ext_crs.xml
> Closes #97

- src/main/scripts/ctl/eowcs_Capabilities.xml
> Closes #121

- src/main/scripts/ctl/DataModel.xml
- src/main/scripts/ctl/ext_get-scal.xml
> Closes #37

- pom.xml
- src/main/java/org/opengis/cite/wcs20/GeometryTransformer.java
- src/main/java/org/opengis/cite/wcs20/Utils.java
- src/main/java/org/opengis/cite/wcs20/exception/UnknownCrsException.java
- src/main/scripts/ctl/eowcs_EO-data-model.xml
- src/main/scripts/ctl/eowcs_functions.xml
- src/test/java/org/opengis/wcs20/test/GeometryTransformTest.java
> Closes #120

- src/main/scripts/ctl/core2main.xml
> Closes #125

- src/main/scripts/ctl/GetCoverage.xml
> Closes #137
